site_name: AASeq
site_url: https://aaseq.com

nav:
  - Home: index.md
  - File Format: fileformat.md

extra_css:
    - css/extra.css

plugins:
    - search

extra:
  generator: false

theme: mkdocs

docs_dir: src
site_dir: out
